import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import Link from 'next/link';
import {signIn, signOut, useSession} from "next-auth/react";

const Home: NextPage = () => {
  const {data: session, status} = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <>
            Sign In first!
            <button onClick={
              (e) => {
                e.preventDefault();
                signIn();
              }
            }>Sign In</button>
          </>
        )}
        {session?.user &&(
          <>
            You are signed In!
            as {session.user.email || session.user.name}
          </>
        )}
      </main>

    </div>
  )
}

export default Home
